use cs175DB

CREATE TABLE IF NOT EXISTS tempTable(
	id VARCHAR(767) PRIMARY KEY, 
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	date_added DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE NOW(),
	object_data LONGBLOB
	);

